### PR TITLE
Fix issue 46 deleting event closes modal

### LINKED ISSUE #46: Deleting an event closes the modal
The title says it all. The modal should stay open when deleting an event.

### PR DESCRIPTION
**Pull request by beaucouplus**
Fixes #46 

What a ride!

Fixing this problem took a whole day.
At first, I had to understand the exact circumstances of the bug. Once I had it, I tried to solve it by using Context with no success, I thought that the failure to render the modal was due to the props that changed and closed the modal. After a while I realized that this was a dead end so I threw away everything I had tried.

Afterwards, I tried another approach by trying to have as few modal renders as possible. It allowed me to refactor quite a lot of components and make them quite dumb. On this path, I finally realized that I should have only one instance of the modal and use context to change its state. It finally got rid of the bug, and once again helped me get rid of quite a bunch of code.

I'm happy, even if I'm not so sure I deeply understand the root problem.

### CODE REVIEW

File: src/features/calendar_views/month_view/EventSummary.js [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+function EventSummary({ date, event }) {
+  const { displayModalAndChooseEvent } = useContext(EventContext);
+
+  const handleClick = (newDate) => {
+    if (typeof newDate === "string") {
+      displayModalAndChooseEvent(newDate, event.id);
+    } else {
+      displayModalAndChooseEvent(date, event.id);
+    }
+  };
```
Comment (beaucouplus) [inline src/features/calendar_views/month_view/EventSummary.js:23]: Not very happy with this code. I either get a newDate as a string, or an event from the dom.

Dunno how to handle it right now. I'll get to it tomorrow certainly.

File: src/features/calendar_views/month_view/EventSummary.js [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+import exact from "prop-types-exact";
+import dayjs from "dayjs";
+
+// CONTEXT
+import { EventContext } from "../../../common/EventContext";
+
+// SCRIPTS
+import { range } from "../../../common/utils";
+
+function EventSummary({ date, event }) {
```
Comment (beaucouplus) [inline src/features/calendar_views/month_view/EventSummary.js:14]: Creating an eventSummary which handles everything for a single event has proven quite useful and got me in the right direction.

It also allowed me to have a single source of truth for events when dealing with modals and get rid of many lines of code along the way.

File: src/features/calendar_views/month_view/WeekRow.js [hunk 3]
```diff
@@ -61,8 +62,8 @@ const WeekDay = ({ day, month, events, maxNumberOfEvents }) => {
 
   const monthDay = dayjs(day).date();
   const titleRef = useRef();
-  const [showModal, setShowModal] = useState(false);
-  const closeModal = () => setShowModal(false);
+
```
Comment (beaucouplus) [inline src/features/calendar_views/month_view/WeekRow.js:65]: I should probably extract WeekDay to its own file, this one would only have direct children of WeekRow and would be more easy to understand.

Also, the prop `day` is difficult to understand and should be replaced by `date`, this would be consistent with the other props in the codebase.

File: src/features/calendar_views/month_view/WeekRow.js [hunk 4]
```diff
@@ -78,22 +79,17 @@ const WeekDay = ({ day, month, events, maxNumberOfEvents }) => {
     future: "bg-white bg-opacity-25 text-gray-700 hover:bg-gray-300 hover:bg-opacity-25 hover:text-black",
   };
 
+  const handleClick = () => displayModal(day);
```
Comment (beaucouplus) [inline src/features/calendar_views/month_view/WeekRow.js:82]: Maybe I can use a custom hook to handle the use of displayModal. I'll give it a try.

File: src/features/calendar_views/month_view/EventSummary.js (hunk 1 above)
Comment (beaucouplus) [reply src/features/calendar_views/month_view/EventSummary.js]: Fixed this by fixing another bug that I found while refactoring. Worth it, the code is way simpler now.

File: src/features/calendar_views/month_view/WeekRow.js (hunk 3 above)
Comment (beaucouplus) [reply src/features/calendar_views/month_view/WeekRow.js]: Fixed. I removed almost every instance of `day` to allow for a better naming.

File: src/features/calendar_views/month_view/WeekRow.js (hunk 4 above)
Comment (beaucouplus) [reply src/features/calendar_views/month_view/WeekRow.js]: Done. It seems difficult at first but it's pretty easy once you've done it once.
